### ISSUE TITLE
Did you forget register `ninja_extra` in `INSTALLED_APPS`

### ISSUE THREAD

**Issue by xuanzc** [lihuacai168/django-ninja-demo#14]
Traceback (most recent call last):
  File "D:\codes\PycharmProjects\mydrf\.venv\lib\site-packages\ninja_extra\operation.py", line 194, in run
    result = self.view_func(request, **values)
  File "D:\codes\PycharmProjects\mydrf\.venv\lib\site-packages\ninja_extra\controllers\route\route_functions.py", line 85, in as_view
    RouteContext, service_resolver(RouteContext)
  File "D:\codes\PycharmProjects\mydrf\.venv\lib\site-packages\ninja_extra\dependency_resolver.py", line 31, in service_resolver
    injector = get_injector()
  File "D:\codes\PycharmProjects\mydrf\.venv\lib\site-packages\ninja_extra\dependency_resolver.py", line 21, in get_injector
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ninja_extra app is not installed. Did you forget register `ninja_extra` in `INSTALLED_APPS`

**Comment by xuanzc** [comment]
sorry, is not django-ninja-demo

**Comment by xuanzc** [comment]
sorry, is not django-ninja-demo

**Comment by lihuacai168** [comment]
try to limit django-ninja to versions before 1.0
